id: AB44AEE50
base_file: fA74B.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:01:45.147249
  last_modified_at: 2022-05-30 22:01:45.147257
